# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 01:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expressions',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Please check the name entry', regex='([\\w\\-_]+)')]),
        ),
    ]
